# Generated by Django 4.0 on 2023-05-19 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=30)),
                ('ci', models.CharField(max_length=10, unique=True)),
                ('direccion', models.CharField(max_length=50)),
                ('telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
    ]
