# Generated by Django 4.0 on 2023-05-23 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajera',
            fields=[
                ('item', models.CharField(help_text='Numero item', max_length=5, unique=True)),
                ('fecha_ingreso', models.DateField()),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.persona')),
            ],
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['-apellidos', 'nombres']},
        ),
    ]
