# Generated by Django 4.0 on 2023-05-23 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_cajera_alter_persona_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficial',
            fields=[
                ('item', models.CharField(help_text='Numero item', max_length=5, unique=True)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha ingreso: ')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.persona')),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('numero', models.CharField(max_length=15, unique=True)),
                ('fecha_ingreso', models.DateField(verbose_name='Fecha ingreso: ')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='administracion.persona')),
            ],
        ),
        migrations.AlterField(
            model_name='cajera',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha ingreso: '),
        ),
    ]
