# Generated by Django 4.0 on 2023-05-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_oficial_socio_alter_cajera_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='fecha_nacimiento',
            field=models.DateTimeField(null=True),
        ),
    ]
